### ISSUE TITLE
gpsEntry

### ISSUE THREAD

**Issue by kimmansur** [Sherbeeny/gps2gform#1]
I'm having issues to correctly locate the field in my forms. How you defined which forms field will be filled?

**Comment by Sherbeeny** [comment]
**Tally forms:**
You have to create a Hidden Field and a Logical Condition that changes the answer of the location field based on the value of the hidden field. Name the hidden field and use that name in the gps2form URL.

**Google forms:**
check this for how to pre-fill a form:
https://www.howtogeek.com/774169/how-to-prefill-google-forms-with-certain-answers/

Fill the location field and extract the "entry questions number" from the prefilled URL. Use that number in the gps2form URL.
